myName = input("What is your name? ")
myAge = input("How old are you? ")
print("Gee, that's REALLY OLD")
replit = input("do you like Replit? ")
print("OF COURSE YOU DO!")

print()
print("So, you are")
print(myName)
print("and are the ripe old age of")
print(myAge)
print("and clearly think that Replit is")
print(replit)

print()
print()
print("syntax error fixes")
print()
myVariable = input("WHO GOES THERE? ")
print(myVariable)
myGrandma = input("How's your Grandma doing? 😘 ")
print(myGrandma)

myLunch = input("What are you having for lunch? ")
print("Hmm, it sounds like you really should just order")
print(myLunch)
print("as soon as possible!")

print()
print()
print("code needing fixed below")
print()

print("Definitely not a Phishing Scam")
print()
myName = input("Your Name")
print("Thanks for logging in")
print(myName)
cardNumber = input("What is your credit card number?")
print("Thanks, I definitely wont put")
print(cardNumber)
print("into Amazon and order anything weird")
print()
print("Promise")
maidenName = input("What is your Mother's maiden name? ")
print()
print("That's cool, I just wanted to know that")
print(maidenName)
print(
    "was your Mum's maiden name. Not because the bank requested it or anything, honest."
)
