myName = input("What is your name? ")
favFood = input("What is your favorite food? ")
favMusic = input("What is your favorite music? ")
myLocation = input("Where do you live? ")
print()
print()
print("Getting to know you!")
print()
print()
print("you are")
print(myName)
print("You're probably hungry for")
print(favFood)
print("and you're definitly getting your groove on to")
print(favMusic)
print("living in the amazing")
print(myLocation)